2025-09-07 12:20:37,492 - ERROR - \u062e\u0637\u0627 \u062f\u0631 \u062a\u0648\u0644\u06cc\u062f \u0646\u0645\u0648\u062f\u0627\u0631 \u067e\u0631\u0627\u06a9\u0646\u062f\u06af\u06cc: 'AdvancedFinancialPredictorUI' object has no attribute 'FigureCanvas'
Traceback (most recent call last):
  File "c:\Users\IraniaN\OneDrive\Desktop\Ai-data-2\visualization.py", line 86, in show_scatter_plot
    self.parent.canvas = self.parent.FigureCanvas(self.parent.figure)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AdvancedFinancialPredictorUI' object has no attribute 'FigureCanvas'
2025-09-07 12:28:22,292 - ERROR - \u0627\u0646\u062a\u062e\u0627\u0628 \u0646\u0627\u0645\u0639\u062a\u0628\u0631: \u06f2 \u06cc\u0627 \u06f3 \u0633\u062a\u0648\u0646 \u0645\u0648\u0631\u062f \u0646\u06cc\u0627\u0632 \u0627\u0633\u062a.
2025-09-07 12:46:53,689 - ERROR - \u062a\u0639\u062f\u0627\u062f \u0633\u062a\u0648\u0646\u200c\u0647\u0627\u06cc \u0627\u0646\u062a\u062e\u0627\u0628\u200c\u0634\u062f\u0647 \u0646\u0627\u0645\u0639\u062a\u0628\u0631 \u0627\u0633\u062a: 1 \u0633\u062a\u0648\u0646 \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:51:46,999 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:51:49,241 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:51:51,761 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:51:53,986 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:51:55,824 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:51:58,323 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:52:00,362 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:52:02,436 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 03:52:07,079 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 04:08:19,746 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 04:09:00,842 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 04:09:04,219 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 04:09:07,986 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 04:09:12,446 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-11 04:09:15,685 - ERROR - \u0633\u062a\u0648\u0646 \u0647\u062f\u0641 \u063a\u06cc\u0631\u0639\u062f\u062f\u06cc \u0627\u0646\u062a\u062e\u0627\u0628 \u0634\u062f\u0647 \u0627\u0633\u062a.
2025-09-13 11:31:45,863 - ERROR - \u062e\u0637\u0627 \u062f\u0631 \u062a\u0648\u0644\u06cc\u062f \u0646\u0645\u0648\u062f\u0627\u0631 \u067e\u0631\u0627\u06a9\u0646\u062f\u06af\u06cc: 400: \u0647\u0645\u0647 \u0633\u062a\u0648\u0646\u200c\u0647\u0627\u06cc \u0627\u0646\u062a\u062e\u0627\u0628\u200c\u0634\u062f\u0647 \u0628\u0627\u06cc\u062f \u0639\u062f\u062f\u06cc \u0628\u0627\u0634\u0646\u062f.
Traceback (most recent call last):
  File "c:\Users\IraniaN\OneDrive\Desktop\Ai-data-2\app.py", line 170, in show_scatter_plot
    raise HTTPException(status_code=400, detail="\u0647\u0645\u0647 \u0633\u062a\u0648\u0646\u200c\u0647\u0627\u06cc \u0627\u0646\u062a\u062e\u0627\u0628\u200c\u0634\u062f\u0647 \u0628\u0627\u06cc\u062f \u0639\u062f\u062f\u06cc \u0628\u0627\u0634\u0646\u062f.")
fastapi.exceptions.HTTPException: 400: \u0647\u0645\u0647 \u0633\u062a\u0648\u0646\u200c\u0647\u0627\u06cc \u0627\u0646\u062a\u062e\u0627\u0628\u200c\u0634\u062f\u0647 \u0628\u0627\u06cc\u062f \u0639\u062f\u062f\u06cc \u0628\u0627\u0634\u0646\u062f.
2025-09-13 12:50:17,461 - ERROR - \u062e\u0637\u0627 \u062f\u0631 \u067e\u0627\u06a9\u200c\u0633\u0627\u0632\u06cc \u062f\u0627\u062f\u0647\u200c\u0647\u0627: single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "c:\Users\IraniaN\OneDrive\Desktop\Ai-data-2\data_processing.py", line 47, in clean_data
    df_cleaned[non_numeric_cols] = df_cleaned[non_numeric_cols].fillna(df_cleaned[non_numeric_cols].mode().iloc[0])
                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\IraniaN\AppData\Roaming\Python\Python311\site-packages\pandas\core\indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IraniaN\AppData\Roaming\Python\Python311\site-packages\pandas\core\indexing.py", line 1752, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\Users\IraniaN\AppData\Roaming\Python\Python311\site-packages\pandas\core\indexing.py", line 1685, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
